export const JOB_PROFILES = [
  "Software Engineer", "Frontend Developer", "Backend Developer", "Full Stack Developer",
  "Mobile App Developer", "DevOps Engineer", "Site Reliability Engineer", "Cloud Engineer",
  "Data Engineer", "Data Scientist", "Machine Learning Engineer", "AI Engineer",
  "Cybersecurity Analyst", "Network Engineer", "QA Engineer", "Automation Test Engineer",
  "Product Manager", "Project Manager", "Program Manager", "Product Designer",
  "UX Designer", "UI Designer", "Graphic Designer", "Content Designer",
  "Business Analyst", "Systems Analyst", "Financial Analyst", "Data Analyst",
  "Accountant", "Auditor", "Investment Banker", "Financial Advisor",
  "Marketing Manager", "Digital Marketing Specialist", "SEO Specialist", "Brand Manager",
  "Sales Executive", "Account Executive", "Business Development Manager", "Customer Success Manager",
  "Human Resources Manager", "Recruiter", "Talent Acquisition Specialist", "People Operations Specialist",
  "Operations Manager", "Supply Chain Manager", "Procurement Specialist", "Logistics Coordinator",
  "Medical Assistant", "Registered Nurse", "Healthcare Administrator", "Pharmacist",
  "Teacher", "Instructional Designer", "Research Scientist", "Legal Counsel",
  "Paralegal", "Journalist", "Public Relations Specialist", "Administrative Assistant",
];
